# Configuration file

# Add your own packages here
# then add an install script in the /commands directory
packages = [
  "alacritty",
  "btop",
  "ca-certificates",
  "cowsay",
  "ddcutil",
  "discord",
  "docker",
  "fzf",
  "golang",
  "lazygit",
  "nala",
  "neofetch",
  "neovim",
  "setup",
  "tldr",
  "trash-cli",
  "webeep-sync",
  "zsh",
]

# Add your own distro here
# then add a directory in the /commands directory
# with all the install scripts
[[distros]]
name = "fedora"
package_manager = "dnf"

[[distros]]
name = "ubuntu"
package_manager = "apt"
