# Configuration file

# Add your own packages here
# then add an install script in the /commands directory
packages = [
  "alacritty",
  "neovim",
  "hyprland",
  "zsh",
  "docker",
  "webeep-sync",
  "discord",
  "nerdfont",
  "src/commands/test",
  "src/commands/test2",
  "src/commands/bad-test",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
]

# Add your own distro here
# then add a directory in the /commands directory
# with all the install scripts
distros = [
  "fedora",
  "ubuntu",
]
